server:
servlet:
context-path: /delivery/api


spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://LuizRefosco:wQ3PABLBw7Eoq89E@luiz.flz3eml.mongodb.net/delivery?retryWrites=true&w=majority}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /public/swagger


delivery:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}
